version: '3'
services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    expose:
      - "1883"
    ports:
      - "9001:9001"
      - "1883:1883"
    volumes:
      - ".:/mosquitto/"